freeswitch:
  image: ianblenke/freeswitch-video
  env_file: .env
  links:
  - igd

igd:
  net: host
  privileged: yes
  build: docker-igd/
  env_file: .env
  links:
  - minissdpd

minissdpd:
  net: host
  privileged: yes
  build: docker-minissdpd/
  env_file: .env
  links:
  - miniupnpd

miniupnpd:
  net: host
  privileged: yes
  build: docker-miniupnpd/
  env_file: .env
