freeswitch:
  image: ianblenke/freeswitch-video
  env_file: .env

igd:
  net: host
  privileged: yes
  build: docker-igd/
  env_file: .env

minissdpd:
  net: host
  privileged: yes
  build: docker-minissdpd/
  env_file: .env

miniupnpd:
  net: host
  privileged: yes
  build: docker-miniupnpd/
  env_file: .env
